# Generated by Django 3.0.7 on 2020-06-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Jacket',
        ),
    ]
